diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: left_wheel_joint
  right_wheel: right_wheel_joint
  publish_rate: 50
  cmd_vel_timeout: 0.5
  velocity_rolling_window_size: 2
  use_stamped_vel: false
