# Full set of configurations
- ros_topic_name: "/diff_cont/cmd_vel_unstamped"
  gz_topic_name: "/model/fejemis/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: false
  direction: ROS_TO_GZ

- ros_topic_name: "/scan"
  gz_topic_name: "/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: false
  direction: GZ_TO_ROS

- ros_topic_name: "/scan/points"
  gz_topic_name: "/lidar/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: false
  direction: GZ_TO_ROS


- ros_topic_name: "/image"
  gz_topic_name: "/world/test_world/model/fejemis/link/base_link/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: false
  direction: GZ_TO_ROS

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: false
  direction: GZ_TO_ROS

# - ros_topic_name: "/model/fejemis/odometry"
#   gz_topic_name: "/model/fejemis/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   subscriber_queue: 10
#   publisher_queue: 10
#   lazy: false
#   direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/fejemis/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: false
  direction: GZ_TO_ROS
  
  