# Full set of configurations
- ros_topic_name: "/diff_cont/cmd_vel_unstamped"
  gz_topic_name: "/model/fejemis/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: false
  direction: ROS_TO_GZ

- ros_topic_name: "/cmd_vel_key"
  gz_topic_name: "/model/fejemis/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: true
  direction: ROS_TO_GZ




- ros_topic_name: "/cmd_vel_joy"
  gz_topic_name: "/model/fejemis/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  subscriber_queue: 100
  publisher_queue: 100
  lazy: false
  direction: ROS_TO_GZ